# Generated by Django 5.0.1 on 2024-03-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('org_type', models.CharField(choices=[('oldage', 'Old-Age'), ('children', 'Children')], default='oldage', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='charityDetails1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
